backend:
  image:
    repository: 100.96.184.94:30500/gymbros-backend
    tag: v1.4.8
  replicas: 1

frontend:
  image:
    repository: 100.96.184.94:30500/gymbros-frontend
    tag: v1.4.8
  replicas: 1

database:
  storage: 5Gi