backend:
  image:
    repository: chrisgthomsen/gymbros-backend
    tag: v1.3.0
  replicas: 1

frontend:
  image:
    repository: chrisgthomsen/gymbros-frontend
    tag: v1.3.1
  replicas: 1

database:
  storage: 5Gi