apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  hivemindcloud.server: |
    hivemindcloud.dk:53 {
      hosts {
        {{- range .Values.hosts }}
        {{ $.Values.ingressClusterIP }} {{ . }}
        {{- end }}
        fallthrough
      }
      whoami
    }
